### ISSUE TITLE
[feature request] i18n

### ISSUE THREAD

**Issue by trebmuh** [brummer10/Mamba#10]
Hi @brummer10 .
It'd be great if mamba could be i18n-ised.
I'd be willing to provide a French translation.

**Comment by brummer10** [comment]
Hi @trebmuh 
Yes, I'll add that.

**Comment by brummer10** [comment]
Done.
You could build a *.po file for your language with `make po` then you could do the translation. After that build Mamba with `make nls` that will enable the i18n support and build the *.mo files from the *.po files.

regards
hermann

**Comment by trebmuh** [comment]
Thanks !
Closing here then.

_To the conscientious reader, see #13 for the French translation._

**Comment by brummer10** [comment]
Hi @trebmuh 

Some things have changed message with and some adjustments for the translations may be needed. 
(I've update the pot file)
I'll push out a new release at last on 15.10.
In case you push a updated translation till then it could be include in the release. 
regards
hermann

**Comment by trebmuh** [comment]
Thanks for pinguing me.
Done in #17 .
