### ISSUE TITLE
i18n issues (French l10n)

### ISSUE THREAD

**Issue by trebmuh** [brummer10/Mamba#14]
Following #13 , I've build it and so far so good, it seems to work like a charm.

A few possible improvements here to get it perfect!

----
**1.** There are some places where the space allocated is too small to handle the French localised strings, such as:

![mamba-trans-1](https://user-images.githubusercontent.com/8705846/92149370-35f68780-ee1e-11ea-9248-9251867275ef.png)
![mamba-trans-3](https://user-images.githubusercontent.com/8705846/92150108-39d6d980-ee1f-11ea-9ada-a4dfdd8caa2b.png)

Is there some way from your (coding) side to allow for more space and/or automatic spacing please?

----

**2.** One untranslated strings (File -> Load) and one (UTF-8 ?) issue:

![mamba-trans-2](https://user-images.githubusercontent.com/8705846/92150137-44916e80-ee1f-11ea-9eb8-5c45b9c375c8.png)

----

**3.** Clicking the _Mapping -> Keymap Editor_ segfaults when the GUI is in French but displays the Editor if launched in English (`LANG=C mamba`). No message from the terminal.

----

That's my current findings.

**Comment by brummer10** [comment]
Hi @trebmuh 
Thanks for your feedback.
I could solve most of this issues now. So, the menu is now auto-sized, the labels for the combo boxes get enough space to show the French labels,  as well the labels in the file selectors get enough space now and  all been marked for translation now. Also the Utf8 issue with the window title is solved. Also the segfault on Mapping -> Keymap Editor in French is solved now. 
Remaining issues been: I cant give the label on the Knobs and the Record button more space, there simply is no space left in horizontal. Is it possible to use shorts for them? 
For mnemonic labels (_Label), there is a restriction to 32 chars. This is to keep it all lightweight. Longer ones will be truncate (now, as that is the reason for the segfault). 
Also for mnemonic labels, the hot keys been hard coded, so when a French label didn't have the char for the hot-key, it may be better to leave the underline alone, instead mark a wrong char. 

regards
hermann

**Comment by trebmuh** [comment]
Hey @brummer10 , with your changes and #15, all is good now from my perspectives.
I've reverted the hotkeys for now.

**Comment by trebmuh** [comment]
There seems to be an issue here:

![mamba-i18n-issue](https://user-images.githubusercontent.com/8705846/92306541-2a2ad280-ef90-11ea-84e2-979af2862e44.png)

What is this "_" character after "Charger MIDI (l)" ?

**Comment by brummer10** [comment]
It's were  a char underline is replaced with a drawn underline, as most font sets didn't come with underline, so you need to draw it instead using simply the font. Here, my calculation comes to a wrong position for the underline as it should be under the (l), I'll investigate.

**Comment by trebmuh** [comment]
OK, thanks for the explanation.

**Comment by brummer10** [comment]
So I've fixed the issue with the mnemonic labels and pushed a new release out.

**Comment by trebmuh** [comment]
Awesome. Thanks Hermann!

Closing here then.
