### ISSUE TITLE
GUI resize issue

### ISSUE THREAD

**Issue by mxmilkiib** [brummer10/Mamba#25]
Resizing the window (awesomewm) upsets the UI;

![image](https://user-images.githubusercontent.com/108225/99154451-c582a700-26a7-11eb-96e8-ac02541e33d0.png)

**Comment by brummer10** [comment]
I don't have awesomewm installed, just guess, is it resized in height or just stretched in width?

**Comment by mxmilkiib** [comment]
Both. I think it respects the ICCCM size hint https://github.com/awesomeWM/awesome/search?q=size_hints_honor which I know mpv uses.

Fullscreen is chibi;
![image](https://user-images.githubusercontent.com/108225/99154827-b05b4780-26aa-11eb-8dc1-f17511032467.png)

**Comment by brummer10** [comment]
Mamba set in XSetWMNormalHints a fixed height, only scaling in width is allowed. So it seems awesomewm didn't respect ICCCM.
This is no issue with any other window manager I've tested so far.

**Comment by brummer10** [comment]
However, thanks for the report. 
And because it is better to handle even unexpected scaling, I've implement a fix for that now in mamba. 
Let me know please if it fix the issue for you.

**Comment by mxmilkiib** [comment]
That all resizes perfectly now :)
