### ISSUE TITLE
Icon has a too light icon resolution

### ISSUE THREAD

**Issue by Houston4444** [brummer10/Mamba#27]
Hi !
The provided Mamba.png icon is 24x24 pixels only.
That is quite ugly when it is shown with higher size, like it can be the case in the main desktop menu, in RaySession or Agordejo.
However, the application icon (when Mamba is running) is fine, so I suppose it uses a vector image even if I can't found any .svg file.
Maybe Mamba could provide a .svg icon directly to desktop, and everything would we ok.

**Comment by brummer10** [comment]
Hi
Okay, I've pushed the svg to the repository. It will be installed and used instead the previous png.
Still I leave the png in the source tree, but it wouldn't be installed any more. 
(I keep it in the uninstall so that could be removed when you run make uninstall)

**Comment by Houston4444** [comment]
thanks a lot !
