### ISSUE TITLE
[feature request] Easier/faster adjustment octave mapping

### ISSUE THREAD

**Issue by grammoboy2** [brummer10/Mamba#28]
You can easily switch channel, bank etc. in Mamba, but for mapping different octave you need to go to the menu, so you need 3 clicks to change it (if you know where to do it). Would be nice if that would be the same as for channel, bank etc.

**Comment by brummer10** [comment]
I've had it in earlier versions like that, now, there is simply no space left in the GUI, that's why I put it in the menu. 
All I could do is implement keyboard shortcuts for it, like ALT & 1, ALT & 2, . . . to make it better accessible.

**Comment by grammoboy2** [comment]
Maybe you can make it possible to hide things? Which then makes space for other stuff?
Like hiding the 'menu bar' with the knobs.
Maybe make a special 'menu bar' for the transport options.

**Comment by brummer10** [comment]
I've pushed keyboard shortcuts for it now. You could use ctrl + 0 <-> 4 for the octave mapping.

**Comment by grammoboy2** [comment]
![screenshot_mamba_ingen](https://user-images.githubusercontent.com/378249/101155897-17c04380-3628-11eb-8e22-91e83e4c94b1.png)
