### ISSUE TITLE
[Idea] Mamba as LV2

### ISSUE THREAD

**Issue by grammoboy2** [brummer10/Mamba#29]
Just a quick wild idea. Make Mamba as LV2 plugin, which you can load in Ingen (with embedded GUI)

**Comment by brummer10** [comment]
I'll do the midi looper as LV2 plugin, but not the keyboard itself.

**Comment by grammoboy2** [comment]
Closing. Would prefer a minimal mode. As LV2 plugin is probably not the best thing.
https://github.com/brummer10/Mamba/issues/31
