### ISSUE TITLE
Manual file searching with computer keyboard

### ISSUE THREAD

**Issue by grammoboy2** [brummer10/Mamba#30]
When trying to load sf file, you need to use your mouse and your mouse only. Would be nice if I could enter the path with my computer keyboard.

**Comment by brummer10** [comment]
Usually you'll have all your soundfonts in the same path, don't you? 
So after select the path, the easiest way to switch a soundfont is the combobox in the Fluidsynth settings window.
If you don't want to have the settings window open, there is also the resent file collection in the menu.
True, you need to use the mouse to do so. But even if I make the path selection in the File selector window editable, you properly need to use the mouse to enable the edit function, as it shouldn't be the default option anyway.

**Comment by brummer10** [comment]
Also, note that you could load a soundfont as well by drag and drop.
