### ISSUE TITLE
Make a minimal mode 

### ISSUE THREAD

**Issue by grammoboy2** [brummer10/Mamba#31]
Idea: Make a 'minimal mode' for Mamba. Where the goal is to make Mamba take as less screenspace as possible, but still being nice to use.

This is useful when you want to use Mamba with Ingen, AMS and those kind of synths.

See also: https://github.com/brummer10/Mamba/issues/28#issuecomment-738718631

**Comment by brummer10** [comment]
there is already in git the option to show/hide controls and bank/program. 
so when hide those only the keyboard is visible.

**Comment by grammoboy2** [comment]
Nice, thanks.

Maybe add a shortcut (preferable one key like 'v' and 'c' or something) to enable/disable the views?

I've a issue when I try to resize (fluxbox/lxde)

![mamba_resize0](https://user-images.githubusercontent.com/378249/102015925-9589fa80-3d5e-11eb-8382-09344d4d90dd.png)

**Comment by grammoboy2** [comment]
The missing topbar is not a issue in the previous screenshot (decorade fluxbox)

![mamba_resize1](https://user-images.githubusercontent.com/378249/102016063-37a9e280-3d5f-11eb-8d5b-3926ee00febe.png)

**Comment by grammoboy2** [comment]
What could be improved is the size of the keys. See for example jack-keyboard, which has a nice keyboard layout I think

![mamba_keysize](https://user-images.githubusercontent.com/378249/102016149-bacb3880-3d5f-11eb-9659-66e86bdaec38.png)

**Comment by brummer10** [comment]
> I've a issue when I try to resize (fluxbox/lxde)

That should be fixed now in git.


> The missing topbar is not a issue in the previous screenshot (decorade fluxbox)

fixed as well.

> What could be improved is the size of the keys. See for example jack-keyboard, which has a nice keyboard layout I think

I've add a new menu entry under View were you could select between "Normal" and "Small" key-size now, also you could shrink the height of the keyboard now, when only the keyboard is visible.

**Comment by grammoboy2** [comment]
Nice work!

If I shrink the keys vertically, then I've the size I'm looking for (see screenshot). So maybe that could be the default for the small interface. That's nitpicking. It's already more pleasant to work with imho. 

![mamba_small](https://user-images.githubusercontent.com/378249/102198602-e0248780-3ec2-11eb-9383-6b53fa4ab1fa.png)

**Comment by brummer10** [comment]
Thanks, I'm glad you like it.
I understand that this is your personal preference, still I prefer the normal size. However, your settings will be saved on exit (If you save) so you only need to shrink it once for each of your NSM sessions and be done.

**Comment by grammoboy2** [comment]
You must have a bigger screen then I have ;)
Thanks again.
