### ISSUE TITLE
Support microtonal scales

### ISSUE THREAD

**Issue by Popolon** [brummer10/Mamba#32]
https://sevish.com/scaleworkshop/ allow to export custom scales.
By using the menu New -> "Subharmonic series segments" you can test an example of micro-tonale scale as used in Arabian, Balkan Indian and Turkish musics.

[Scala](http://huygens-fokker.org/scala/)  (.scl files) is probably a great reference in micro-tonal music research softwares, but I don't know much more about all those formats.

**Comment by brummer10** [comment]
That is out of scope for mamba, sorry.

**Comment by brummer10** [comment]
Hi @Popolon 
I've just pushed support for microtonal scales from 10 to 22-edo to Mamba. Still, that didn't mean any scala support.
