### ISSUE TITLE
Custom key mapping for chromatic keyboards (for example a button accordion)

### ISSUE THREAD

**Issue by balajahe** [brummer10/Mamba#34]
Thanks for the great program!

Regarding custom key mapping - there is one mistake and one wish.

1) There is no way to specify the "Enter" key.

2) The program is perfect for modeling chromatic keyboards (for example a button accordion), but duplication of keys is typical for them, that is, I need the ability to assign several different keys to the same note. Unfortunately, there is no such possibility in any virtual midi keyboard I know.
https://en.wikipedia.org/wiki/Chromatic_button_accordion

Thank you!

**Comment by brummer10** [comment]
Hi
Okay, I guess duplication of keys will be enough then?
I've implemented now the possibility to setup 2 keys per note in the custom keymap editor.
Also you could use the enter key now.
regards
hermann

**Comment by balajahe** [comment]
Great, thank you very much for your promptness, I'll check it tomorrow!
PS
I use your keyboard in conjunction with Ardor, the main advantage is the lack of latency, which was noticed with VMPK.

**Comment by balajahe** [comment]
I was able to simulate the keyboard of a 4-row button accordion using the upper row of numeric keys. The "Backspace" key fits perfectly into this row, if possible, add its support please!
PS
In general, I am very pleased, there is a small suspicion that there is a slight time delay on the duplicated keys, but this is inaccurate, you need to further monitor.

**Comment by brummer10** [comment]
Good to hear you like it. 

To the suspicion that there is slight time delay on the duplicated keys: That is very unlikely. From the logic it is implemented you may be more likely be able to hear a delay from C1 to C2 then from key1 to key2. But we talk about a fraction of a microsecond here. I take a lot of care to avoid any delay in reaction of the keyboard, even for the duplicated keys.

>  The "Backspace" key fits perfectly into this row, if possible, add its support please!

Sorry, but this is used to edit the Keymap editor (remove key), so it will be a bit tricky to support it as key for the keyboard. Truth is, we could use the delete key for this, but, don't react on the Backspace key by remove the last entry means leaving the xdg specifications. Tricky, I'm not sure I would do that, even if I understand your request.

**Comment by brummer10** [comment]
I do some measurement on the response time, it's between 2-3µs (microsecond), regardless which key is pressed.

**Comment by balajahe** [comment]
everything's working just fine!
