### ISSUE TITLE
[FR] Grab keyboard hotkey

### ISSUE THREAD

**Issue by KottV** [brummer10/Mamba#36]
Hi,

I've found that Mamba has the cool feature to capture keypress being unfocused. But to toggle that option you have to use mouse.
What if to add some hotkey for switch on/off "Grab keyboard"?
I suppose that "on" will work while Mamba is focused only, and "off" when it's not in front too.

**Comment by brummer10** [comment]
Hi
Yes, good idea. As it was easy to do it's done. 
You could use `ctrl + g` now to de/activate the grab keyboard mode.

**Comment by KottV** [comment]
Thank you!
