### ISSUE TITLE
Ignore key repeat

### ISSUE THREAD

**Issue by jn64** [brummer10/Mamba#40]
Hi, using Mamba 2.2 on Fedora 33 / GNOME 3.38. I have key repeat enabled for typing purposes.

When I hold a key in Mamba, it repeats (repeatedly triggering the note).

In comparison, in other virtual MIDI keyboards like [jack-keyboard](https://sourceforge.net/projects/jack-keyboard/), trackers, and other music software, it does not repeat. It behaves like a piano key (hold = sustain).

Is it possible for Mamba to also ignore key repeat and behave like a piano key?

**Comment by brummer10** [comment]
> When I hold a key in Mamba, it repeats (repeatedly triggering the note).

Hi, that is strange, as Mamba is set to don't auto repeat. 

> Is it possible for Mamba to also ignore key repeat and behave like a piano key?

That's exactly how it behave here. 
Do you build Mamba from source and do you've a bit programming experience? Maybe we could find out why it didn't work for you.
regards
hermann

**Comment by jn64** [comment]
I am using the build from [Fedora copr ycollet/linuxmao](https://copr.fedorainfracloud.org/coprs/ycollet/linuxmao/), the [rpm .spec file can be found here](https://github.com/audinux/fedora-spec/blob/master/guitarix/mamba.spec).

I'm not C programmer but can follow instructions :) I will try build from source and see if there is the same issue.

**Comment by brummer10** [comment]
So I've installed Gnome and could reproduce the issue. 
I've pushed a fix for it to the repository. 
When you build from source, let me know if that fix it for you as well.

**Comment by jn64** [comment]
I was going to ask what I can do to help troubleshoot, but you already fixed it!

I can confirm the issue was present when building from source in 80ed348, and fixed in d0f5fe4.

Thank you very much!
