### ISSUE TITLE
Mamba closes/stops in non-session-manager instead of hiding it's GUI

### ISSUE THREAD

**Issue by grammoboy2** [brummer10/Mamba#43]
When I close mamba from it's own gui, while running in non-session-manager, it ... closes/stops. But I think it would be better if it would hide in that case when under nsm and let the user use the nsm gui to stop it.

**Comment by brummer10** [comment]
I know there are a couple of assumptions about how a client under NSM control should behave.  But, I like to revert this to the user. If you would control Mamba from the NSM GUI, just do that, all options been supported. If not, use the controls Mamba provide (and be ensured that Mamba forward this info to the NSM controller). Still, even when you've quit Mamba from it's internal menu, you are able to restart it from the NSM controller. If you only would hide Mamba, just do it from the NSM controller.

**Comment by grammoboy2** [comment]
Hm hiding the gui is a more common/regular action then stopping Mamba in a session. So hiding instead of closing, prevents the user from switching back and forth from nsm gui to applications. 
If you want to keep this a user choice, you could maybe add a configuration option, compile option or environment variable.

**Comment by brummer10** [comment]
Okay, so I've implemented your request. Still, when will show the UI again, you've to use the NSM GUI anyway, so the difference is just marginal.
The desktop decorator (x) still close the app.
