### ISSUE TITLE
[FR] MIDI through on/off option in toolbar and/or menu

### ISSUE THREAD

**Issue by SpotlightKid** [brummer10/Mamba#47]
Example use case:

I want to control a hardware keyboard with it, but also route its MIDI out in to Mamba to show what I'm playing on screen. But without a MIDI loop ;)

**Comment by brummer10** [comment]
Done, there is now a check menu entry under Mapping to disable MIDI through.
(I'll tomorrow work over the deprecation warnings from fluidsynth)

**Comment by SpotlightKid** [comment]
Nice! Works perfectly. Thanks!

**Comment by brummer10** [comment]
I've added the new switch now to the saved config file and fixed the fluidsynth API check. 
Therewith I'll close this feature request.
regards
