### ISSUE TITLE
Mamba fails to build on Fedora 38

### ISSUE THREAD

**Issue by plaimbock** [brummer10/Mamba#51]
Hi, thank you for Mamba! I just tried to build git HEAD on Fedora 38 x86_64 and the build fails with:

XAlsa.cpp: In member function 'void xalsa::XAlsa::xalsa_get_ports(std::vector<std::__cxx11::basic_string<char> >*, std::vector<std::__cxx11::basic_string<char> >*)':
XAlsa.cpp:157:34: error: no matching function for call to 'std::vector<std::__cxx11::basic_string<char> >::push_back(char [256])'
  157 |                 iports->push_back(port);
      |                 ~~~~~~~~~~~~~~~~~^~~~~~

Any idea how to solve this error?

**Comment by brummer10** [comment]
Hi 
Thanks for reporting. I've pushed a fix for it to the repository. Let me know if it works for you.

**Comment by plaimbock** [comment]
Thanks for the quick reply! Commit [05aafdb](https://github.com/brummer10/Mamba/commit/05aafdb2278b5f50b148c1ee25dc8cab8ffeee41) results in a different error (see attachment).
[mamba_build_errors.txt](https://github.com/brummer10/Mamba/files/11285253/mamba_build_errors.txt)

**Comment by brummer10** [comment]
Strange, never seen such a error, mean 
`error: aggregate 'std::string p' has incomplete type and cannot be defined`
doing so for years defining empty std::strings without issues. 
Which gcc version do you use? 
However, I've pushed  a other try, maybe that works on your setup.

**Comment by plaimbock** [comment]
No joy. The gcc version is 13.0.1. The build log with the errors is at:
https://download.copr.fedorainfracloud.org/results/patrickl/Mamba/fedora-38-x86_64/05808875-mamba/builder-live.log.gz

**Comment by brummer10** [comment]
Okay. It looks like gcc 13 now requires explicit including string header.  
Before I push a other try could you try to edit XAlsa.h and add
`#include <string>`
right below #include <thread> line 23
if that works I'll push the fix to the repository.

**Comment by plaimbock** [comment]
That works!

Successful build log here: https://download.copr.fedorainfracloud.org/results/patrickl/Mamba/fedora-38-x86_64/05808962-mamba/builder-live.log
