### ISSUE TITLE
Config created in home dir instead of XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by jn64** [brummer10/Mamba#53]
Recently updated from Mamba 2.3 to 2.5 and noticed the file `~/.configMamba.conf` being created, I suspect a `/` is missing somewhere and it should be `~/.config/Mamba.conf`.

**Comment by brummer10** [comment]
Hi
Sorry for late reply. Yes, it's a bug. I've pushed a fix for it now to the repository.
