### ISSUE TITLE
mamba binary segmentation fault

### ISSUE THREAD

**Issue by maccagnan** [brummer10/Mamba#57]
Hello,
 I tried mamba binary today on Devuan Daedalus.
I installed libsmf0 (1.3-4) and ran the binary. Got this error message:
Segmentation fault
Without any further indication.
Any suggestions as to how troubleshoot this issue?

**Comment by brummer10** [comment]
Best solution would be to build it from source. I mean even when we try to debug this segmentation fault, I guess we end up in a scenario were we recognise that the binary is un-compatible with your distribution. It may be related to the fluidsynth version used to build the binary, or, any other lib. 
Building from source isn't that hard when you follow the instructions from the project page. I'm here, if you've any question on that.

**Comment by maccagnan** [comment]
Thanks for the prompt reply.
I'm using Debian Trixie and Fluidsynth verison is 2.3.4-1.
I tried building from source, but get the error:
$pwd
/home/test/Downloads/Mamba-master/Mamba-master
$git submodule init
fatal: not a git repository (or any of the parent directories): .git

**Comment by brummer10** [comment]
You must download the source with 
`git clone https://github.com/brummer10/Mamba.git`
don't use the zip provided by github, that one wouldn't work (it's a ever lasting issue on github for projects using submodules)
after clone go to the top directory
`cd Mamba`
then follow the instrutions on the project page

```
git submodule init
git submodule update
make
```
you could try out Mamba (when it builds successful) as well without install it, by 

`./src/build/mamba`

If you like it you could install it with 
`sudo make install`
and get your menu entry for it.

**Comment by maccagnan** [comment]
I built it and got the same error.

here is the build output

https://codeshare.io/MkjqbQ

**Comment by brummer10** [comment]
Do you've jackd up and running?

**Comment by maccagnan** [comment]
Yes, jack is running, same as fluidsynth.

**Comment by brummer10** [comment]
Strange. I've no idea why it crash for you. Only way to get a hint would be to run a debug build in gdb.
If you've some time and interest to solve this issue, please build a debug version and run it in gdb.
In case you don't have installed gdb you could install it with apt install gdb

```
make clean
make debug
gdb  ./src/build/mamba
```
then, when it crash type
`bt full`
post the result please at [pastebin](https://pastebin.com/)

**Comment by maccagnan** [comment]
It is odd, I'm using debian stable and testing, not any exotic linux distro. Snd the build went fine, no issues. I'll try the debug process when I got time and post the result.

**Comment by brummer10** [comment]
Yes, really odd, as I'm using debian as well, unstable/testing here. So our systems wont be much different at all.

**Comment by maccagnan** [comment]
Okay, I erased everything and started from scratch on Debian stable, reinstalled all the dependencies and recompiled, and now it works. It might be that I missed something, although I couldn't tell what.

**Comment by brummer10** [comment]
Strange. However, nice to hear it works now. 
Hope it will be useful for you as well.

**Comment by maccagnan** [comment]
Thanks for the assistance and for developing this neat software.
