### ISSUE TITLE
segfault on Wayland

### ISSUE THREAD

**Issue by grammoboy2** [brummer10/Mamba#60]
Using arch linux version, works in X11 not in Wayland 

```
$ mamba
Segmentation fault (core dumped)
```

**Comment by brummer10** [comment]
Wayland didn't even works on my machine, so I expect the issue is in wayland.

**Comment by brummer10** [comment]
For clarify, I've partitioned my hard-drive to get a free partition,  installed arch linux wayland (cinnamon) and build mamba from git. So what, it works as it should. 
Takes me a few hours.

**Comment by grammoboy2** [comment]
I got that segfault, I couldn't remember it crashed while using X11, so I tried it in X11 and it worked there. Same for the guitarix issue. I vaguely remembered that one of your libraries has a x in it's name, so I concluded that it could be related to that. I reported those issues, to let you know about them.

**Comment by brummer10** [comment]
Then there must be something different in the path, maybe you use pipewire, or run it under NSM, or , .  . .

**Comment by grammoboy2** [comment]
Could it be wlroots related (sway, dwl, river, ...)? 

Are you sure your Cinnamon uses wayland, as Linux Mint (Cinnamon) is one of the latest distro's which supported wayland afaik.  

Possibly related: https://github.com/brummer10/guitarix/issues/198

**Comment by brummer10** [comment]
I run the test on arch linux. 
However, in the mean time there was development in that field and I found out what the culprit is ( a function call fail under sway) and fixed it in libxputty by implement a guard around that function. I just haven't updated libxputty in mamba in order to get the fix into mamba. 

The issue with nsm under wayland is gtk based, that one I can't fix.

**Comment by grammoboy2** [comment]
> The issue with nsm under wayland is gtk based, that one I can't fix.

So that's hide/show optional-gui related? Do other Gtk based applications have the same issue? IIRC I didn't encounter problems with seq192 for example.
