### ISSUE TITLE
mamba is veryyy long to start on librazik3

### ISSUE THREAD

**Issue by Houston4444** [brummer10/Mamba#8]
On my laptop on librazik3, mamba displays a GUI after at least 7-8 seconds, I think it is very long for this kind of software.
On my desktop on Ubuntu18.04, GUI is displayed in the two first seconds, what is largely acceptable.
There is a little performance difference between the two hardwares, but I can't think this explains the difference.

Note: the stderr messages is written only when GUI appears.
```
Samplerate 48000Hz 
Buffersize is 256 samples 
jack running with realtime priority
```

**Comment by brummer10** [comment]
Last time I tried on debian/buster I noticed as well a time gap during start up. So I go and check it out again today. With the last git I didn't noticed that any more. I implemented a measurement and get a startup time (from enter command to GUI pop up) of ~1.02 sec on debian/buster. 
Please update your checkout and try again if it still takes to long.

**Comment by trebmuh** [comment]
@Houston4444 it looks like it depends of the computer or/and system.
On librazik3, from git ac61360, it takes ~1.73 second for the GUI to appears here.
I'll try from a fresh checkout to see if there is some changes.

**Comment by Houston4444** [comment]
ah ok, sorry for the annoyance.

**Comment by trebmuh** [comment]
After a rebuild from c2cbe1e, it looks to be the same.

**Comment by Houston4444** [comment]
I just saw a similar issue with GNOME desktop.
Also, it was impossible to stop Mamba under NSM, making the session impossible to close under Non Session Manager (and probably also with new-session-manager). This probably means that Mamba is not capable to read the SIGTERM signal.

Note that it appears both with GNOME X and GNOME WAYLAND, and the problem doesn't appears with PLASMA (KDE) WAYLAND. Mamba works well with KDE and MATE.
Still under Librazik3 (Debian Buster).

**Comment by brummer10** [comment]
Strange, I've no problem here with new-session-manager. Start/stop flawless, with and without saving&exit.
I never use Non Session Manager and I've no plan to do so.

**Comment by brummer10** [comment]
I just tested it with raysession, and got no problem at all. [ray-daemon]Commanding Mamba to quit

```
[ray-daemon]Commanding Mamba to quit

[Mamba-mamba]

Mamba: signal 15 received, bye bye ...

[ray-daemon]Commanding JACK Connexions to quit
[ray-daemon]Done

```

**Comment by Houston4444** [comment]
@brummer10. I think this more depends on desktop than session manager. Do you use GNOME ?

> I never use Non Session Manager and I've no plan to do so.
Very good idea, that is just that @trebmuh has not yet replace it with new session manager in LZK3 repos.

Since last update, this behavior appears on all desktops on my laptop, but works very well on my desktop computer (on KDE, I don't wan't to install many desktops on this machine).

**Comment by brummer10** [comment]
I don't have GNOME installed, I using Cinnamon. For testing I've Mate, but there it works flawless. 
I've a live stick with GNOME debian 10, will give it a go tomorrow.

**Comment by Houston4444** [comment]
Hummm, I am not sure it comes from GNOME, now with 1.5 I have the problem on all the D.E of my laptop (kde, mate, gnome), wayland or X.
And still no problem on my desktop computer which has kde only.
@trebmuh seems to have the problem on MATE too.
Pfff... this is so weird.

**Comment by brummer10** [comment]
@Houston4444 
I guess I found the culprit. 
https://github.com/brummer10/Mamba/commit/ce2ae30ecb1a1f29f2e8363de1046fd6b5daa69a
please check latest git if the issue is solved.
regards
hermann

**Comment by trebmuh** [comment]
Nice. Rebuild from ce2ae30 and the problem seems to be gone.
thanks @brummer10

**Comment by Houston4444** [comment]
I confirm there is no more problem with NSM support (tested under RaySession).
I still have a very long start (GUI takes ~= 10s to appear), but this system could be quite broken with 3 D.E. installed (which is a source of trouble).
Thanks @brummer10 ! (and @trebmuh  for the packaging ;))

**Comment by brummer10** [comment]
@Houston4444 
I've already a idea what could lead to the long start time  and working on it. 
Just to confirm my idea,  I guess you've no problem with XTuner regarding the startup time?
If so I could push a update before the weekend which may improve the startup time significant. (here on my computer I reduce it already from   ~0.35 sec to ~0.28 sec. That's not much on my computer, but could make a huge difference on yours were it takes ~10 sec now.

**Comment by Houston4444** [comment]
mmmhh, this system is quite broken (on my laptop), I can't install some XTuner build dependencies and don't know why.
I was trying mamba from librazik package.
I would be not surprised that it could exists a link between the two problems.

**Comment by brummer10** [comment]
> I can't install some XTuner build dependencies and don't know why.

Ups, that sounds indeed broken. There isn't any fancy dependency at all.
However, improving the startup time means as well reducing the memory foot print and so is a good thing. I've pushed the updates to git and wont be surprised when this improve Mamba on your laptop as well. Maybe I pushed a new release next month.

**Comment by trebmuh** [comment]
Super thing @brummer10 , just made a rebuild from a1a18c6, and on one desktop computer where it use to take 8 sec to start, it now take 2 sec. Awesome! Thanks.

**Comment by Houston4444** [comment]
Yes @brummer10  ! between 4 and 5 seconds now ! Thanks.
I may still have to re-install my laptop for others reasons ;)

**Comment by brummer10** [comment]
Thanks for confirming the fix. 
I'm glad that it becomes better.
